id: P009639
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25168
  title: འཇིགས་བྱེད་ཆོས་འབྱུང།
  author: ''
  volumes:
    7f3c2b179a3448439cecd3b6cbe14ca6:
      image_group_id: I1KG25170
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
