id: P009639
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25168
  title: འཇིགས་བྱེད་ཆོས་འབྱུང།
  author: ''
  volumes:
    7f3c2b179a3448439cecd3b6cbe14ca6:
      image_group_id: I1KG25170
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
